// KLINIK SISTEMA — Turso Data Layer v2
// Conecta TODAS as telas do frontend às APIs do Turso
(function(){'use strict'
function apiGet(ep,params){var qs=params?'?'+Object.entries(params).filter(function(kv){return kv[1]!==undefined&&kv[1]!==null&&kv[1]!==''}).map(function(kv){return encodeURIComponent(kv[0])+'='+encodeURIComponent(kv[1])}).join('&'):'';return fetch('/api/'+ep+qs).then(function(r){return r.json()}).then(function(d){return d.success!==false?d:null}).catch(function(e){console.error('API:',ep,e);return null})}
function fmtBrl(v){return'R$ '+(v||0).toLocaleString('pt-BR',{minimumFractionDigits:2})}

// 1. DASHBOARD
window.loadDashboard=async function(){var d=await apiGet('dashboard');if(!d)return;ST.dashboard={resumo:d.resumo,por_mes:{},por_categoria:{},profissionais:d.profissionais||[],inativos:(d.inativos||[]).map(function(p){return{nome:p.nome,ultima:p.ultima_visita?p.ultima_visita.slice(0,10):'—',dias:p.dias_ausente||999,telefone:p.telefone}})};(d.agendamentos_por_mes||[]).forEach(function(m){ST.dashboard.por_mes[m.mes]=m.total});(d.agendamentos_por_categoria||[]).forEach(function(c){ST.dashboard.por_categoria[c.categoria]=c.total});ST.inativos=ST.dashboard.inativos;ST.profissionais=d.profissionais;if(typeof renderCRMCounts==='function')renderCRMCounts(ST.inativos);if(curPage==='crm')renderCRM();if(curPage==='relatorios')renderRelatorios();if(typeof renderRelCounts==='function')renderRelCounts(ST.dashboard);if(typeof renderProfsList==='function')renderProfsList();var r=d.resumo,el;el=document.getElementById('rel-fat');if(el)el.textContent=fmtBrl(r.receita_total);el=document.getElementById('rel-receb');if(el)el.textContent=fmtBrl(r.receita_total);el=document.getElementById('rel-ag');if(el)el.textContent=r.total_agendamentos||0;console.log('[Turso] Dashboard:',r.total_pacientes,'pac,',r.total_agendamentos,'ag')}

// 2. AGENDA
window.loadAgenda=async function(){var le=document.getElementById('agenda-loading'),ge=document.getElementById('agenda-grid');if(le)le.classList.remove('hidden');if(ge)ge.classList.add('hidden');try{var modo=(document.getElementById('agenda-view-sel')||{}).value||'dia';var dtStr=agendaDate.toISOString().slice(0,10);var mesStr=agendaDate.getFullYear()+'-'+String(agendaDate.getMonth()+1).padStart(2,'0');var params={};if(modo==='dia')params={modo:'dia',data:dtStr};else if(modo==='semana')params={modo:'semana',data:dtStr};else if(modo==='mes')params={modo:'mes',mes:mesStr};var d=await apiGet('agenda-view',params);if(d&&d.agendamentos){ST.agendamentos=d.agendamentos.map(function(a){var parts=(a.data_hora||'').split(' ');var hora=parts[1]||'';var h=parseInt((hora.split(':')[0]))||9;var m=parseInt((hora.split(':')[1]))||0;var mF=m+30,hF=h;if(mF>=60){hF++;mF-=60}return{date:parts[0]||'',fromTime:hora,toTime:hF+':'+String(mF).padStart(2,'0'),PatientName:a.paciente_nome||'',CategoryDescription:a.categoria||'',ProfessionalName:a.profissional_nome||'',Deleted:a.status==='cancelado',Status:a.status,_profId:a.profissional_id,MobilePhone:''}});if(d.profissionais){ST.profissionais=d.profissionais;ST.dashboard=ST.dashboard||{};ST.dashboard.profissionais=d.profissionais}if(typeof renderMiniCal==='function')renderMiniCal();if(typeof renderProfsList==='function')renderProfsList();if(typeof renderAgendaGrid==='function')renderAgendaGrid();var we=document.getElementById('agenda-warn-txt');if(we&&d.resumo){var sc=d.resumo.agendados||0;we.textContent=sc>0?sc+' sem confirmação':''}}if(!ST.pacientesLista||ST.pacientesLista.length===0)loadPacTurso();if(le)le.classList.add('hidden');if(ge)ge.classList.remove('hidden')}catch(e){console.error('[Turso] Agenda:',e)}}
window.agendaChangeView=function(){loadAgenda()}

// 3. PACIENTES
async function loadPacTurso(busca,status){var params={limit:100};if(busca)params.busca=busca;if(status)params.status=status;var d=await apiGet('pacientes',params);if(!d)return;ST.pacientesLista=(d.data||[]).map(function(p){return{nome:p.nome,tel:p.telefone||'',email:p.email||'',ultima:p.ultima_visita?new Date(p.ultima_visita):new Date(2020,0,1),id:p.id,dias_ausente:p.dias_ausente}});if(d.resumo){var se=document.getElementById('pac-sub');if(se)se.textContent=d.resumo.total_pacientes+' pacientes ('+d.resumo.total_ativos+' ativos, '+d.resumo.total_inativos+' inativos)'}var le=document.getElementById('pac-loading'),de=document.getElementById('pac-data');if(le)le.classList.add('hidden');if(de)de.classList.remove('hidden');var ce=document.getElementById('pac-count');if(ce)ce.textContent=(d.paginacao?d.paginacao.total:ST.pacientesLista.length)+' pacientes';var li=document.getElementById('pac-list');if(li){li.innerHTML=ST.pacientesLista.slice(0,50).map(function(p){var ini=p.nome.split(' ').slice(0,2).map(function(x){return x[0]||''}).join('');var dias=p.dias_ausente||Math.floor((Date.now()-p.ultima.getTime())/864e5);var inativo=dias>180;var tel=(p.tel||'').replace(/\D/g,'');return'<div class="patient-row"><div class="patient-av">'+ini+'</div><div class="patient-info"><div class="patient-name">'+p.nome+'</div><div class="patient-meta"><span>'+(p.tel||'—')+'</span><span>Última visita: '+p.ultima.toLocaleDateString('pt-BR')+'</span><span>'+dias+' dias</span></div><div class="patient-tags">'+(inativo?'<span class="badge badge-orange">Inativo</span>':'<span class="badge badge-green">Ativo</span>')+'</div></div><div class="patient-acts">'+(tel?'<a href="https://wa.me/55'+tel+'" target="_blank" class="wa-btn">WhatsApp</a>':'')+'<button class="btn btn-sm" onclick="abrirProntuario(\''+p.nome.replace(/'/g,"\\'")+'\')">Prontuário</button></div></div>'}).join('')}if(typeof filterProntList==='function')filterProntList()}
window.renderPacientes=function(){loadPacTurso()}
var _ft=null;window.filterPac=function(){clearTimeout(_ft);_ft=setTimeout(function(){var q=(document.getElementById('pac-search').value||'').trim();var f=document.getElementById('pac-filter').value;var st=f==='inativos'?'inativos':f==='ativos'?'ativos':'';loadPacTurso(q.length>=2?q:'',st)},350)}

// 4. CRC
window.renderCRM=async function(){var f=document.getElementById('crm-filter').value;var d=await apiGet('crc',{prioridade:f==='all'?'':f});if(!d)return;var el;el=document.getElementById('crm-urgente');if(el)el.textContent=d.contagens.urgente;el=document.getElementById('crm-alta');if(el)el.textContent=d.contagens.alta;el=document.getElementById('crm-media');if(el)el.textContent=d.contagens.media;el=document.getElementById('crm-sub');if(el)el.textContent=d.contagens.total+' pacientes sem visita há 6+ meses';var bm={urgente:'badge-red',alta:'badge-orange',media:'badge-green'},lm={urgente:'URGENTE',alta:'ALTA',media:'MÉDIA'};var te=document.getElementById('crm-table');if(te)te.innerHTML=(d.data||[]).map(function(p,i){var tel=(p.telefone||'').replace(/\D/g,'');var n1=(p.nome||'').split(' ')[0];var wa='https://wa.me/55'+tel+'?text='+encodeURIComponent('Olá '+n1+'! É a Klinik Odontologia. Sentimos sua falta!');return'<tr><td class="text-muted">'+(i+1)+'</td><td><div class="pname">'+p.nome+'</div></td><td class="text-muted">'+(p.ultima_visita||'—')+'</td><td style="color:var(--red);font-weight:500">'+(p.dias_ausente||'?')+'d</td><td><span class="badge '+(bm[p.prioridade]||'')+'">'+(lm[p.prioridade]||'')+'</span></td><td>'+(tel?'<a href="'+wa+'" target="_blank" class="wa-btn">WhatsApp</a>':'—')+'</td></tr>'}).join('')}

// 5. CONTA CORRENTE
window.renderCC=async function(){var deV=document.getElementById('dp-de-val'),ateV=document.getElementById('dp-ate-val');var de='',ate='';if(deV){var p=(deV.textContent||'').split('/');if(p.length===3)de=p[2]+'-'+p[1]+'-'+p[0]}if(ateV){var p2=(ateV.textContent||'').split('/');if(p2.length===3)ate=p2[2]+'-'+p2[1]+'-'+p2[0]}if(!de||!ate){var now=new Date();var fr=new Date();fr.setDate(fr.getDate()-7);de=fr.toISOString().slice(0,10);ate=now.toISOString().slice(0,10)}var d=await apiGet('conta-corrente',{de:de,ate:ate});if(!d)return;var el;el=document.getElementById('cc-tot-vendas');if(el)el.textContent=fmtBrl(d.totais.vendas);el=document.getElementById('cc-tot-entrada');if(el)el.textContent=fmtBrl(d.totais.entradas);el=document.getElementById('cc-tot-saida');if(el)el.textContent=fmtBrl(d.totais.saidas);var BM={boleto:'<span class="cc-tx-badge badge-boleto">BOLETO</span>',credito:'<span class="cc-tx-badge badge-credito">CRÉDITO</span>',debito:'<span class="cc-tx-badge badge-debito">DÉBITO</span>',pix:'<span class="cc-tx-badge badge-pix">PIX</span>',transf:'<span class="cc-tx-badge badge-transf">TRANSF.</span>',dinheiro:'<span class="cc-tx-badge badge-dinheiro">DINHEIRO</span>'};var li=document.getElementById('cc-list');if(li)li.innerHTML=(d.dias||[]).map(function(dia,idx){return'<div class="cc-day-expand"><div class="cc-day-header" onclick="ccToggle('+idx+')"><div class="cc-day-badge"><div class="cc-day-num">'+dia.dia_num+'</div><div class="cc-day-mon">'+dia.mes_abr+'</div></div><div class="cc-day-chevron" id="cc-chev-'+idx+'">›</div><div class="cc-day-name">'+dia.dia_semana+'</div><div class="cc-day-vals">'+(dia.entradas>0?'<div class="cc-val-item"><span class="cc-val-lbl">Entrada</span><span style="color:var(--green)">'+fmtBrl(dia.entradas)+'</span></div>':'')+'<div class="cc-val-item"><span class="cc-val-lbl">Saída</span><span style="color:'+(dia.saidas>0?'var(--red)':'var(--text3)')+'">'+fmtBrl(dia.saidas)+'</span></div></div></div><div class="cc-transactions" id="cc-tx-'+idx+'">'+dia.transacoes.map(function(t){return'<div class="cc-tx-row" style="grid-template-columns:80px 90px 1fr 110px"><span class="cc-tx-tipo '+(t.positivo?'entrada':'saida')+'">'+t.tipo+'</span><span>'+(BM[t.badge]||'')+'</span><span class="cc-tx-desc">'+t.descricao+'</span><span class="cc-tx-val '+(t.positivo?'pos':'neg')+'">'+(t.positivo?'+':'-')+fmtBrl(t.valor)+'</span></div>'}).join('')+'</div></div>'}).join('')}

// 6. FLUXO DE CAIXA
window.renderFDC=async function(){var mesEl=document.getElementById('fdc-mes');var MS=['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];var mn=mesEl?(MS.indexOf(mesEl.value)+1||3):3;var d=await apiGet('fluxo-caixa',{mes:mn,ano:2026});if(!d)return;var canvas=document.getElementById('fdc-canvas');if(!canvas)return;if(window.fdcChart){window.fdcChart.destroy();window.fdcChart=null}var filtered=d.por_dia.filter(function(x){return x.entradas>0||x.saidas>0});var labels=filtered.map(function(x){return String(x.dia).padStart(2,'0')+'/'+String(mn).padStart(2,'0')});var ent=filtered.map(function(x){return x.entradas});var sai=filtered.map(function(x){return-x.saidas});var sacum=filtered.map(function(x){return x.acumulado});if(typeof Chart!=='undefined'){window.fdcChart=new Chart(canvas,{data:{labels:labels,datasets:[{type:'bar',label:'Entrada',data:ent,backgroundColor:'#4CAF50',yAxisID:'y'},{type:'bar',label:'Saída',data:sai,backgroundColor:'#F44336',yAxisID:'y'},{type:'line',label:'Acumulado',data:sacum,borderColor:'#1565C0',backgroundColor:'transparent',pointRadius:3,tension:.3,yAxisID:'y'}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{ticks:{maxRotation:0,font:{size:9}}},y:{ticks:{font:{size:9},callback:function(v){return Math.abs(v)>=1000?v/1000+'k':v}}}},animation:{duration:400}}})}var el;el=document.getElementById('fdc-sum-mes');if(el)el.textContent=MS[mn-1]||'';el=document.getElementById('fdc-sum-ent');if(el)el.textContent=fmtBrl(d.totais.entradas);el=document.getElementById('fdc-sum-sai');if(el)el.textContent=fmtBrl(d.totais.saidas);el=document.getElementById('fdc-sum-sal');if(el)el.textContent=fmtBrl(d.totais.saldo);var rc=document.querySelector('.fdc-resumo-cards');if(rc&&d.resumo_entradas)rc.innerHTML=(d.resumo_entradas||[]).map(function(r){return'<div class="fdc-resumo-card"><div class="fdc-resumo-card-title">'+(r.forma_pagamento||'Outros')+'</div><div class="fdc-resumo-card-val">'+fmtBrl(r.total)+'</div></div>'}).join('')}

// 7. PROFISSIONAIS
window.loadProfissionais=async function(){var le=document.getElementById('prof-loading'),de=document.getElementById('prof-data');if(le)le.classList.remove('hidden');if(de)de.classList.add('hidden');var d=await apiGet('profissionais');if(!d||!d.data)return;ST.profissionais=d.data;var se=document.getElementById('prof-sub');if(se)se.textContent=d.data.length+' profissionais';var CO=['#9C27B0','#4CAF50','#FF9800','#795548','#2196F3','#E91E63','#00BCD4','#F44336'];var ge=document.getElementById('prof-grid');if(ge)ge.innerHTML=d.data.map(function(p,i){var ini=(p.nome||'').split(' ').slice(0,2).map(function(x){return x[0]||''}).join('');var cor=CO[i%CO.length];return'<div class="prof-card"><div class="prof-av" style="background:'+cor+'22;color:'+cor+'">'+ini+'</div><div class="prof-name">'+(p.nome||'')+'</div><div class="prof-esp">'+(p.especialidade||'')+'</div><div style="margin-top:8px;font-size:11px;color:var(--text3)">'+(p.total_agendamentos||0)+' agendamentos</div><div style="font-size:11px;color:var(--green)">'+(p.agendamentos_mes||0)+' este mês</div><span class="badge badge-green" style="margin-top:8px">Ativo</span></div>'}).join('');if(typeof renderProfsList==='function')renderProfsList();if(le)le.classList.add('hidden');if(de)de.classList.remove('hidden')}

// 8. ANIVERSARIANTES
window.loadAniversariantes=async function(){var le=document.getElementById('aniv-loading'),de=document.getElementById('aniv-data');if(le)le.classList.remove('hidden');if(de)de.classList.add('hidden');var d=await apiGet('aniversariantes');if(!d)return;var MM=['','JAN','FEV','MAR','ABR','MAI','JUN','JUL','AGO','SET','OUT','NOV','DEZ'];var li=document.getElementById('aniv-list');if(li)li.innerHTML=(d.data||[]).length?(d.data||[]).map(function(a){var tel=(a.telefone||'').replace(/\D/g,'');var n1=(a.nome||'').split(' ')[0];var ps=(a.dia_aniversario||'').split('-');var dia=ps[2]||'?',mes=ps[1]?MM[parseInt(ps[1])]:'?';var wa='https://wa.me/55'+tel+'?text='+encodeURIComponent('Feliz aniversário, '+n1+'! A equipe Klinik te deseja um dia incrível!');return'<div style="display:flex;align-items:center;gap:12px;padding:10px 0;border-bottom:1px solid var(--border)"><div style="width:40px;text-align:center;background:rgba(27,94,59,.08);border-radius:6px;padding:4px"><div style="font-size:18px;font-weight:300;color:var(--green)">'+dia+'</div><div style="font-size:9px;color:var(--text3)">'+mes+'</div></div><div style="flex:1"><div style="font-weight:500;font-size:13px">'+a.nome+'</div><div style="font-size:12px;color:var(--text3)">'+(a.telefone||'—')+' · em '+a.dias_faltam+' dias</div></div>'+(tel?'<a href="'+wa+'" target="_blank" class="wa-btn">Parabenizar</a>':'')+'</div>'}).join(''):'<div style="text-align:center;padding:30px;color:var(--text3)">Nenhum aniversariante</div>';if(le)le.classList.add('hidden');if(de)de.classList.remove('hidden')}

// 9. FINANCEIRO
window.loadFinanceiro=async function(){var d=await apiGet('financeiro',{limit:60});if(!d)return;ST.recebimentos=d.data||[];var t=d.totais||{},el;el=document.getElementById('fin-total');if(el)el.textContent=fmtBrl(t.total_geral);el=document.getElementById('fin-ticket');if(el)el.textContent='R$ '+(t.total_registros>0?Math.round(t.total_geral/t.total_registros):0).toLocaleString('pt-BR');el=document.getElementById('fin-count');if(el)el.textContent=t.total_registros||0;var te=document.getElementById('fin-table');if(te)te.innerHTML=(d.data||[]).slice(0,60).map(function(r,i){return'<tr><td class="text-muted">'+(i+1)+'</td><td><div class="pname">'+(r.descricao||'—')+'</div></td><td class="text-muted">'+(r.data_pagamento||'—')+'</td><td style="color:var(--green);font-weight:500">'+fmtBrl(r.valor)+'</td></tr>'}).join('');ST._finData=d.data;var le=document.getElementById('fin-loading'),de=document.getElementById('fin-data');if(le)le.classList.add('hidden');if(de)de.classList.remove('hidden')}

// 10. BUSCA GLOBAL
window.globalSearch=async function(q){if(!q||q.length<2)return;var lo=q.toLowerCase();var pgs=['agenda','pacientes','financeiro','relatorios','configuracoes','profissionais','crm','aniversariantes'];var m=pgs.find(function(p){return p.includes(lo)||lo.includes(p.substring(0,4))});if(m&&q.length>3){nav(m);return}var d=await apiGet('busca',{q:q});if(!d||d.total===0)return;if(d.pacientes&&d.pacientes.length>0){nav('pacientes');var se=document.getElementById('pac-search');if(se){se.value=q;filterPac()}}}

// 11. RELATÓRIOS
window.renderRelatorios=function(){var d=ST.dashboard;if(!d)return;if(typeof renderRelCounts==='function')renderRelCounts(d);var sorted=Object.entries(d.por_mes).sort(function(a,b){return a[0].localeCompare(b[0])}).slice(-6);var max=Math.max.apply(null,sorted.map(function(x){return x[1]}))||1;var MA=['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'];var ce=document.getElementById('rel-chart');if(ce&&sorted.length>0)ce.innerHTML=sorted.map(function(it){var ps=it[0].split('-');return'<div style="flex:1;display:flex;flex-direction:column;align-items:center;gap:4px"><div style="font-size:10px;color:var(--text3)">'+it[1]+'</div><div style="height:'+Math.max(4,Math.round(it[1]/max*90))+'px;width:100%;background:rgba(27,94,59,.6);border-radius:2px 2px 0 0;max-width:36px"></div><div style="font-size:10px;color:var(--text3)">'+MA[parseInt(ps[1])-1]+'</div></div>'}).join('');var cats=Object.entries(d.por_categoria).sort(function(a,b){return b[1]-a[1]}).slice(0,10);var tc=cats.reduce(function(s,c){return s+c[1]},0)||1;var pe=document.getElementById('rel-proc');if(pe)pe.innerHTML=cats.map(function(c){return'<tr><td class="pname">'+c[0]+'</td><td>'+c[1]+'</td><td style="color:var(--text3)">'+Math.round(c[1]/tc*100)+'%</td></tr>'}).join('');var pre=document.getElementById('rel-profs');if(pre&&ST.profissionais)pre.innerHTML=(ST.profissionais||[]).map(function(p){return'<tr><td class="pname">'+(p.nome||'—')+'</td><td class="text-muted">'+(p.total_agendamentos||0)+'</td></tr>'}).join('');var ina=d.inativos||[],el;el=document.getElementById('rel-urg');if(el)el.textContent=ina.filter(function(i){return i.dias>365}).length;el=document.getElementById('rel-alta');if(el)el.textContent=ina.filter(function(i){return i.dias>270&&i.dias<=365}).length;el=document.getElementById('rel-med');if(el)el.textContent=ina.filter(function(i){return i.dias<=270}).length}

// 12. DASHBOARD ANALÍTICO
window.renderDashAnalitico=async function(){var prod=await apiGet('relatorios',{tipo:'producao',meses:3});if(prod&&prod.producao_mensal){var MA=['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'];var max=Math.max.apply(null,prod.producao_mensal.map(function(m){return m.agendamentos}))||1;var ce=document.getElementById('chart-caixa');if(ce)ce.innerHTML=prod.producao_mensal.map(function(m){var rec=(prod.receita_mensal||[]).find(function(r){return r.mes===m.mes})||{};var ps=m.mes.split('-');return'<div class="bar-grp" style="flex:1"><div class="bar-grp-bars"><div class="bar-seg" style="height:'+Math.max(4,Math.round((rec.receita||0)/Math.max(max*50,1)*90))+'px;background:#1976D2" title="Receita: '+fmtBrl(rec.receita)+'"></div><div class="bar-seg" style="height:'+Math.max(4,Math.round(m.agendamentos/max*90))+'px;background:#F9A825" title="'+m.agendamentos+' ag"></div></div><div class="bar-lbl">'+MA[parseInt(ps[1])-1]+'</div></div>'}).join('')}}

// 13. PRONTUÁRIO
window.abrirProntuario=async function(nome){nav('prontuario');var pac=await apiGet('pacientes',{busca:nome,limit:1});if(!pac||!pac.data||pac.data.length===0)return;var det=await apiGet('pacientes',{id:pac.data[0].id});if(!det)return;var p=det.paciente,ags=det.agendamentos||[],fin=det.financeiro||[];var ts=[18,17,16,15,14,13,12,11,21,22,23,24,25,26,27,28];var ti=[48,47,46,45,44,43,42,41,31,32,33,34,35,36,37,38];var de=document.getElementById('pront-detail');if(de){var h='<div class="card" style="margin-bottom:12px"><div class="card-header"><div class="card-title">'+p.nome+'</div></div><div class="card-body"><span class="badge badge-blue">'+ags.length+' consultas</span> <span class="badge badge-green">'+fin.length+' financeiro</span>'+(p.telefone?' <span style="margin-left:8px;color:var(--text3)">'+p.telefone+'</span>':'')+'</div></div>';h+='<div class="card" style="margin-bottom:12px"><div class="card-header"><div class="card-title">Odontograma</div></div><div style="padding:4px 8px;font-size:10px;text-align:center;color:var(--text3)">SUPERIOR</div><div class="odont-row">'+ts.map(function(t){return'<div><div class="tooth">'+t+'</div></div>'}).join('')+'</div><div class="odont-row">'+ti.map(function(t){return'<div><div class="tooth">'+t+'</div></div>'}).join('')+'</div><div style="padding:4px 8px;font-size:10px;text-align:center;color:var(--text3)">INFERIOR</div></div>';h+='<div class="card"><div class="card-header"><div class="card-title">Histórico</div></div><div class="card-body p0"><table class="tbl"><thead><tr><th>Data</th><th>Categoria</th><th>Profissional</th><th>Status</th></tr></thead><tbody>'+ags.map(function(a){return'<tr><td>'+(a.data_hora||'—').slice(0,10)+'</td><td><span class="badge badge-blue">'+(a.categoria||'')+'</span></td><td>'+(a.profissional||'—')+'</td><td>'+(a.status||'')+'</td></tr>'}).join('')+'</tbody></table></div></div>';if(fin.length>0)h+='<div class="card" style="margin-top:12px"><div class="card-header"><div class="card-title">Financeiro</div></div><div class="card-body p0"><table class="tbl"><thead><tr><th>Data</th><th>Descrição</th><th>Valor</th></tr></thead><tbody>'+fin.map(function(f){return'<tr><td>'+(f.data_pagamento||'—')+'</td><td>'+(f.descricao||'—')+'</td><td style="color:var(--green)">'+fmtBrl(f.valor)+'</td></tr>'}).join('')+'</tbody></table></div></div>';de.innerHTML=h}if(typeof filterProntList==='function')filterProntList()}

console.log('[Klinik Turso v2] Todas as telas conectadas')
})()
